// automatically generated by the FlatBuffers compiler, do not modify

package User1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type logins struct {
	_tab flatbuffers.Table
}

func GetRootAslogins(buf []byte, offset flatbuffers.UOffsetT) *logins {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &logins{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *logins) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *logins) Logs(obj *login, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *logins) LogsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func loginsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func loginsAddLogs(builder *flatbuffers.Builder, logs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(logs), 0)
}
func loginsStartLogsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func loginsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
