// automatically generated by the FlatBuffers compiler, do not modify

package User1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type lol struct {
	_tab flatbuffers.Struct
}

func (rcv *lol) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *lol) Id() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *lol) MutateId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func Createlol(builder *flatbuffers.Builder, id int32) flatbuffers.UOffsetT {
	builder.Prep(4, 4)
	builder.PrependInt32(id)
	return builder.Offset()
}
